# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Junsik's Blog
tagline:             always work in progress
description:         a place to think and study
url:                 junsikshim.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Junsik Shim
  url:               https://github.com/junsikshim
  email:             junsik.shim@gmail.com

# Custom vars
version:             1.0.0

gems:                [jekyll-paginate]